2021-01-11 12:14:52,345 - [test_01register.py-->line:44] - ERROR: 用例注册成功-带注册名成功
2021-01-11 12:14:52,865 - [test_01register.py-->line:44] - ERROR: 用例成功-不带用户名成功
2021-01-11 12:14:53,095 - [test_01register.py-->line:44] - ERROR: 用例不输入手机号成功
2021-01-11 12:14:53,345 - [test_01register.py-->line:44] - ERROR: 用例手机号长度10位成功
2021-01-11 12:14:53,585 - [test_01register.py-->line:44] - ERROR: 用例手机号长度12位成功
2021-01-11 12:14:53,835 - [test_01register.py-->line:44] - ERROR: 用例手机号含有非法字符成功
2021-01-11 12:14:54,184 - [test_01register.py-->line:44] - ERROR: 用例已注册过的手机号成功
2021-01-11 12:14:54,424 - [test_01register.py-->line:44] - ERROR: 用例密码7位成功
2021-01-11 12:14:54,674 - [test_01register.py-->line:44] - ERROR: 用例密码17位成功
2021-01-11 12:14:54,904 - [test_01register.py-->line:44] - ERROR: 用例不输入密码成功
2021-01-11 12:14:55,144 - [test_01register.py-->line:44] - ERROR: 用例注册名11位成功
2021-01-11 12:14:55,384 - [test_01register.py-->line:44] - ERROR: 用例类型输入非0，1内容成功
2021-01-11 12:14:55,691 - [test_01register.py-->line:40] - ERROR: 用例手机号为字符串类型失败
2021-01-11 12:14:55,691 - [test_01register.py-->line:41] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\HD\Desktop\qianchengdai\testcase\test_01register.py", line 33, in test_01_register
    self.assertEqual(expected["code"], res["code"])
  File "D:\测试\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\测试\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-01-11 12:14:55,861 - [test_02login.py-->line:36] - ERROR: 用例登录成功失败
2021-01-11 12:14:55,861 - [test_02login.py-->line:37] - ERROR: 0 != 1001
Traceback (most recent call last):
  File "C:\Users\HD\Desktop\qianchengdai\testcase\test_02login.py", line 33, in test_02_login
    self.assertEqual(expected["code"], res["code"])
  File "D:\测试\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\测试\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 1001
2021-01-11 12:14:55,951 - [test_02login.py-->line:40] - ERROR: 用例手机号为空成功
2021-01-11 12:14:56,031 - [test_02login.py-->line:40] - ERROR: 用例密码为空成功
2021-01-11 12:14:56,191 - [test_02login.py-->line:40] - ERROR: 用例手机号未注册成功
2021-01-11 12:14:56,346 - [test_02login.py-->line:40] - ERROR: 用例密码错误成功
2021-01-11 12:14:56,431 - [test_02login.py-->line:40] - ERROR: 用例手机号格式错误成功
